// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCn8cOj2PftnsGQsXU3tmNEnQQxuDFFA',
    appId: '1:315678174319:web:57b3c6bc259785d26bf19a',
    messagingSenderId: '315678174319',
    projectId: 'my-talks-app',
    authDomain: 'my-talks-app.firebaseapp.com',
    storageBucket: 'my-talks-app.appspot.com',
    measurementId: 'G-ET2VDKJRFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcPtzeC8PfK5mEJbDim0eKLOXM9MH1KpQ',
    appId: '1:315678174319:android:599644d3091cc6d16bf19a',
    messagingSenderId: '315678174319',
    projectId: 'my-talks-app',
    storageBucket: 'my-talks-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgR85juHr02AUs2ReNWC_07hEn2V4958',
    appId: '1:315678174319:ios:eb64bc9aff134f886bf19a',
    messagingSenderId: '315678174319',
    projectId: 'my-talks-app',
    storageBucket: 'my-talks-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFgR85juHr02AUs2ReNWC_07hEn2V4958',
    appId: '1:315678174319:ios:eb64bc9aff134f886bf19a',
    messagingSenderId: '315678174319',
    projectId: 'my-talks-app',
    storageBucket: 'my-talks-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnCn8cOj2PftnsGQsXU3tmNEnQQxuDFFA',
    appId: '1:315678174319:web:836c46a573ed21536bf19a',
    messagingSenderId: '315678174319',
    projectId: 'my-talks-app',
    authDomain: 'my-talks-app.firebaseapp.com',
    storageBucket: 'my-talks-app.appspot.com',
    measurementId: 'G-77XF4SPJM7',
  );
}
